### ISSUE TITLE
twig dump

### ISSUE THREAD

**Issue by ajakov** [umutphp/php-var-dump-check-action#1]
Hi @umutphp 

Can this action check for **dump** in twig files?

Like, for example:
`{{ dump() }}` 
or 
`{{ dump(variable) }}`

**Comment by umutphp** [comment]
Hi @ajakov ,

Yes, you need to use `checktype: 'symfony'`.

You can configure as follows;

```yaml
on: [push]

jobs:
  var_dump_checker:
    runs-on: ubuntu-latest
    name: Dump Function Checks
    steps:
    - name: Check 1
      id: check1
      uses: umutphp/php-var-dump-check-action@v1
      with:
        checktype: 'symfony'
        exclude: 'vendor,test'
        extensions: 'php'
```
