### ISSUE TITLE
Not working with symfony : actions starts on github but it succeed even if I had a dump.

### ISSUE THREAD

**Issue by GeoDaz** [umutphp/php-var-dump-check-action#2]
Hello, you're project seems realy good. 
I use github actions to deploy my symfony app and it works correctly.
I tried your pipeline to check dumps on this project before merging a pull request.
So I had this : 
`/.github/workflows/push.yml` : 
```yml
on: [push]

jobs:
  push-test:
    runs-on: ubuntu-latest
    name: Push Test
    steps:
    - name: Dump Check
      id: dumpcheck
      uses: umutphp/php-var-dump-check-action@v1
      with:
        checktype: 'symfony'
        exclude: 'vendor,test'
        extensions: 'php'
```
When I push on this test-branch, the action starts at each push.
But, even if I add a dump or a var_dump in a controller, the action still succeed.
I didn't find more doc about your project to check if I missed a requirement.
The file ".php" is in `/src/Controller/Api/`.
I try too on `/public/index.php`.
Even with a simple php file on the root, it's not working.
`/foo.php` :
```php
<?php 

var_dump('thing');
```

**Comment by umutphp** [comment]
Hi @GeoDaz ,

Many thanks for the issue :).

I think you have forgotten to add checkout step to your GitHub action yml. The file may be as follows;

```
on: [push]

jobs:
  push-test:
    runs-on: ubuntu-latest
    name: Push Test
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Dump Check
      id: dumpcheck
      uses: umutphp/php-var-dump-check-action@v1
      with:
        checktype: 'symfony'
        exclude: 'vendor,test'
        extensions: 'php'
```

Can you please try and update me?
